import Navbar from '../components/Navbar';
import Providers from '../components/SessionProvider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
      <Providers>
          <div className='container'>
            <Navbar/>
          </div>
          {children}
        </Providers>
      </body>
    </html>
  )
}
