import Navbar from '../components/Navbar';
import Providers from '../components/SessionProvider';
import ScrollUp from '../components/ScrollUp';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <head><link rel="shortcut" href="#"/></head>
      <body>
        <Providers>
          <div className='container'>
            <Navbar/>
          </div>
          <ScrollUp/>
          {children}
        </Providers>
      </body>
    </html>
  )
}
