import {Navbar} from '../components/Navbar';
import {AuthProvider} from '../components/SessionProvider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <head></head>
      <body>
        <AuthProvider>
          <div className='container'>
            <Navbar/>
          </div>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
